apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: devsmd-user-service.minikube
      http:
        paths:
          - path: /user
            backend:
              serviceName: devsmd-user-service
              servicePort: 8000
