apiVersion: v1
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: devsmd-employer-service                # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: devsmd-employer-service
spec:
  type: NodePort                              # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: devsmd-employer-service               # Selects any Pod with labels `app=golang-app-postgres`
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: http